---
language: php

sudo: false

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - XDEBUG_MODE=coverage

before_script:
  - (composer self-update; true)
  - composer install

script:
  - composer test
